### ISSUE TITLE
Add todo functionality

### ISSUE THREAD

**Issue by AH-Huynh942** [AH-Huynh942/one-note-for-all#1]
# Summary
Basic function of creating todos and adding them to a list

# Requirements
- [x] Add a input field
- [ ] The value of that input field is displayed in a list
- [ ] For the now there is only one list called the "main list"
- [ ] The main list is a vertical display of todos
- [ ] Centralize todo input field
- [ ] Centralize TODO display list
